# Generated by Django 5.0.14 on 2026-06-01 01:15

from django.db import migrations


def seed_celulares(apps, schema_editor):
    Celular = apps.get_model('store', 'Celular')
    celulares = [
        Celular(marca='Samsung',    modelo='Galaxy S24 Ultra',   precio='1299.99', stock=15),
        Celular(marca='Apple',      modelo='iPhone 16 Pro Max',  precio='1399.99', stock=10),
        Celular(marca='Xiaomi',     modelo='Redmi Note 13 Pro',  precio='399.99',  stock=25),
        Celular(marca='Motorola',   modelo='Edge 50 Pro',        precio='699.99',  stock=20),
        Celular(marca='Huawei',     modelo='P60 Pro',            precio='899.99',  stock=8),
        Celular(marca='Samsung',    modelo='Galaxy A55',         precio='449.99',  stock=30),
        Celular(marca='Apple',      modelo='iPhone 15',          precio='799.99',  stock=12),
        Celular(marca='Xiaomi',     modelo='Poco X6 Pro',        precio='349.99',  stock=18),
    ]
    Celular.objects.bulk_create(celulares)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_celulares),
    ]
