precio_base=float(input("Precio base del celular: "))
iva=float(input("Porcentaje de IVA: "))
print("Precio con IVA")
print(precio_base, "+", iva, precio_base + precio_base * iva / 100)
print("Descuento")
print(precio_base, "-", iva, precio_base - iva)
print("Cuotas (3 meses)")
print(precio_base, "*", 3, precio_base * 3)
print("Cuota mensual")
print(precio_base, "/", 3, precio_base / 3)
print("Comision vendedor")
print(precio_base, "%", iva, precio_base % iva)
print("Interes compuesto 12 meses")
print(precio_base, "**", 2, precio_base ** 2)
